{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting sentence-transformers\n",
      "  Downloading sentence_transformers-3.4.1-py3-none-any.whl.metadata (10 kB)\n",
      "Requirement already satisfied: scikit-learn in c:\\users\\cheta\\python\\venv\\lib\\site-packages (1.6.1)\n",
      "Requirement already satisfied: pandas in c:\\users\\cheta\\python\\venv\\lib\\site-packages (2.2.3)\n",
      "Requirement already satisfied: numpy in c:\\users\\cheta\\python\\venv\\lib\\site-packages (2.2.3)\n",
      "Collecting transformers<5.0.0,>=4.41.0 (from sentence-transformers)\n",
      "  Downloading transformers-4.49.0-py3-none-any.whl.metadata (44 kB)\n",
      "Requirement already satisfied: tqdm in c:\\users\\cheta\\python\\venv\\lib\\site-packages (from sentence-transformers) (4.67.1)\n",
      "Collecting torch>=1.11.0 (from sentence-transformers)\n",
      "  Downloading torch-2.6.0-cp311-cp311-win_amd64.whl.metadata (28 kB)\n",
      "Requirement already satisfied: scipy in c:\\users\\cheta\\python\\venv\\lib\\site-packages (from sentence-transformers) (1.15.2)\n",
      "Collecting huggingface-hub>=0.20.0 (from sentence-transformers)\n",
      "  Downloading huggingface_hub-0.29.1-py3-none-any.whl.metadata (13 kB)\n",
      "Requirement already satisfied: Pillow in c:\\users\\cheta\\python\\venv\\lib\\site-packages (from sentence-transformers) (11.1.0)\n",
      "Requirement already satisfied: joblib>=1.2.0 in c:\\users\\cheta\\python\\venv\\lib\\site-packages (from scikit-learn) (1.4.2)\n",
      "Requirement already satisfied: threadpoolctl>=3.1.0 in c:\\users\\cheta\\python\\venv\\lib\\site-packages (from scikit-learn) (3.5.0)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in c:\\users\\cheta\\python\\venv\\lib\\site-packages (from pandas) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in c:\\users\\cheta\\python\\venv\\lib\\site-packages (from pandas) (2025.1)\n",
      "Requirement already satisfied: tzdata>=2022.7 in c:\\users\\cheta\\python\\venv\\lib\\site-packages (from pandas) (2025.1)\n",
      "Collecting filelock (from huggingface-hub>=0.20.0->sentence-transformers)\n",
      "  Downloading filelock-3.17.0-py3-none-any.whl.metadata (2.9 kB)\n",
      "Collecting fsspec>=2023.5.0 (from huggingface-hub>=0.20.0->sentence-transformers)\n",
      "  Downloading fsspec-2025.2.0-py3-none-any.whl.metadata (11 kB)\n",
      "Requirement already satisfied: packaging>=20.9 in c:\\users\\cheta\\python\\venv\\lib\\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (24.2)\n",
      "Collecting pyyaml>=5.1 (from huggingface-hub>=0.20.0->sentence-transformers)\n",
      "  Downloading PyYAML-6.0.2-cp311-cp311-win_amd64.whl.metadata (2.1 kB)\n",
      "Requirement already satisfied: requests in c:\\users\\cheta\\python\\venv\\lib\\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2.32.3)\n",
      "Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\\users\\cheta\\python\\venv\\lib\\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (4.12.2)\n",
      "Requirement already satisfied: six>=1.5 in c:\\users\\cheta\\python\\venv\\lib\\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)\n",
      "Collecting networkx (from torch>=1.11.0->sentence-transformers)\n",
      "  Downloading networkx-3.4.2-py3-none-any.whl.metadata (6.3 kB)\n",
      "Requirement already satisfied: jinja2 in c:\\users\\cheta\\python\\venv\\lib\\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.5)\n",
      "Collecting sympy==1.13.1 (from torch>=1.11.0->sentence-transformers)\n",
      "  Downloading sympy-1.13.1-py3-none-any.whl.metadata (12 kB)\n",
      "Collecting mpmath<1.4,>=1.1.0 (from sympy==1.13.1->torch>=1.11.0->sentence-transformers)\n",
      "  Downloading mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)\n",
      "Requirement already satisfied: colorama in c:\\users\\cheta\\python\\venv\\lib\\site-packages (from tqdm->sentence-transformers) (0.4.6)\n",
      "Requirement already satisfied: regex!=2019.12.17 in c:\\users\\cheta\\python\\venv\\lib\\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2024.11.6)\n",
      "Collecting tokenizers<0.22,>=0.21 (from transformers<5.0.0,>=4.41.0->sentence-transformers)\n",
      "  Downloading tokenizers-0.21.0-cp39-abi3-win_amd64.whl.metadata (6.9 kB)\n",
      "Collecting safetensors>=0.4.1 (from transformers<5.0.0,>=4.41.0->sentence-transformers)\n",
      "  Downloading safetensors-0.5.3-cp38-abi3-win_amd64.whl.metadata (3.9 kB)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in c:\\users\\cheta\\python\\venv\\lib\\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.2)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in c:\\users\\cheta\\python\\venv\\lib\\site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.4.1)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\users\\cheta\\python\\venv\\lib\\site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.10)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\users\\cheta\\python\\venv\\lib\\site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2.3.0)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\users\\cheta\\python\\venv\\lib\\site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2025.1.31)\n",
      "Downloading sentence_transformers-3.4.1-py3-none-any.whl (275 kB)\n",
      "Downloading huggingface_hub-0.29.1-py3-none-any.whl (468 kB)\n",
      "Downloading torch-2.6.0-cp311-cp311-win_amd64.whl (204.2 MB)\n",
      "   ---------------------------------------- 0.0/204.2 MB ? eta -:--:--\n",
      "   ---------------------------------------- 1.3/204.2 MB 6.1 MB/s eta 0:00:34\n",
      "    --------------------------------------- 3.1/204.2 MB 8.0 MB/s eta 0:00:26\n",
      "    --------------------------------------- 4.5/204.2 MB 7.3 MB/s eta 0:00:28\n",
      "   - -------------------------------------- 5.2/204.2 MB 6.5 MB/s eta 0:00:31\n",
      "   - -------------------------------------- 6.6/204.2 MB 6.3 MB/s eta 0:00:32\n",
      "   - -------------------------------------- 7.6/204.2 MB 6.1 MB/s eta 0:00:33\n",
      "   - -------------------------------------- 8.9/204.2 MB 6.1 MB/s eta 0:00:33\n",
      "   - -------------------------------------- 10.0/204.2 MB 6.0 MB/s eta 0:00:33\n",
      "   -- ------------------------------------- 11.0/204.2 MB 5.9 MB/s eta 0:00:33\n",
      "   -- ------------------------------------- 11.8/204.2 MB 5.6 MB/s eta 0:00:35\n",
      "   -- ------------------------------------- 12.6/204.2 MB 5.4 MB/s eta 0:00:36\n",
      "   -- ------------------------------------- 13.4/204.2 MB 5.4 MB/s eta 0:00:36\n",
      "   -- ------------------------------------- 14.4/204.2 MB 5.3 MB/s eta 0:00:36\n",
      "   -- ------------------------------------- 15.2/204.2 MB 5.2 MB/s eta 0:00:37\n",
      "   --- ------------------------------------ 16.0/204.2 MB 5.1 MB/s eta 0:00:38\n",
      "   --- ------------------------------------ 16.8/204.2 MB 5.0 MB/s eta 0:00:38\n",
      "   --- ------------------------------------ 18.1/204.2 MB 5.1 MB/s eta 0:00:37\n",
      "   --- ------------------------------------ 19.1/204.2 MB 5.1 MB/s eta 0:00:37\n",
      "   --- ------------------------------------ 19.1/204.2 MB 5.1 MB/s eta 0:00:37\n",
      "   --- ------------------------------------ 19.4/204.2 MB 4.7 MB/s eta 0:00:40\n",
      "   --- ------------------------------------ 19.7/204.2 MB 4.5 MB/s eta 0:00:41\n",
      "   --- ------------------------------------ 19.9/204.2 MB 4.5 MB/s eta 0:00:42\n",
      "   --- ------------------------------------ 19.9/204.2 MB 4.5 MB/s eta 0:00:42\n",
      "   --- ------------------------------------ 20.2/204.2 MB 4.0 MB/s eta 0:00:46\n",
      "   ---- ----------------------------------- 20.4/204.2 MB 4.0 MB/s eta 0:00:47\n",
      "   ---- ----------------------------------- 21.0/204.2 MB 3.9 MB/s eta 0:00:48\n",
      "   ---- ----------------------------------- 21.2/204.2 MB 3.8 MB/s eta 0:00:49\n",
      "   ---- ----------------------------------- 21.2/204.2 MB 3.8 MB/s eta 0:00:49\n",
      "   ---- ----------------------------------- 21.8/204.2 MB 3.6 MB/s eta 0:00:52\n",
      "   ---- ----------------------------------- 23.1/204.2 MB 3.6 MB/s eta 0:00:50\n",
      "   ---- ----------------------------------- 24.9/204.2 MB 3.8 MB/s eta 0:00:47\n",
      "   ----- ---------------------------------- 26.7/204.2 MB 4.0 MB/s eta 0:00:45\n",
      "   ----- ---------------------------------- 27.8/204.2 MB 4.0 MB/s eta 0:00:44\n",
      "   ----- ---------------------------------- 29.1/204.2 MB 4.1 MB/s eta 0:00:43\n",
      "   ----- ---------------------------------- 30.4/204.2 MB 4.1 MB/s eta 0:00:42\n",
      "   ------ --------------------------------- 32.0/204.2 MB 4.2 MB/s eta 0:00:41\n",
      "   ------ --------------------------------- 33.8/204.2 MB 4.4 MB/s eta 0:00:40\n",
      "   ------ --------------------------------- 35.7/204.2 MB 4.5 MB/s eta 0:00:38\n",
      "   ------- -------------------------------- 37.2/204.2 MB 4.5 MB/s eta 0:00:37\n",
      "   ------- -------------------------------- 39.3/204.2 MB 4.7 MB/s eta 0:00:36\n",
      "   ------- -------------------------------- 40.6/204.2 MB 4.7 MB/s eta 0:00:35\n",
      "   -------- ------------------------------- 42.7/204.2 MB 4.8 MB/s eta 0:00:34\n",
      "   -------- ------------------------------- 44.0/204.2 MB 4.9 MB/s eta 0:00:33\n",
      "   -------- ------------------------------- 44.6/204.2 MB 4.9 MB/s eta 0:00:33\n",
      "   -------- ------------------------------- 44.8/204.2 MB 4.8 MB/s eta 0:00:34\n",
      "   -------- ------------------------------- 45.1/204.2 MB 4.7 MB/s eta 0:00:34\n",
      "   -------- ------------------------------- 45.9/204.2 MB 4.6 MB/s eta 0:00:35\n",
      "   --------- ------------------------------ 46.9/204.2 MB 4.7 MB/s eta 0:00:34\n",
      "   --------- ------------------------------ 48.8/204.2 MB 4.7 MB/s eta 0:00:33\n",
      "   --------- ------------------------------ 50.1/204.2 MB 4.8 MB/s eta 0:00:33\n",
      "   ---------- ----------------------------- 51.4/204.2 MB 4.8 MB/s eta 0:00:32\n",
      "   ---------- ----------------------------- 53.0/204.2 MB 4.8 MB/s eta 0:00:32\n",
      "   ---------- ----------------------------- 54.5/204.2 MB 4.9 MB/s eta 0:00:31\n",
      "   ---------- ----------------------------- 56.1/204.2 MB 4.9 MB/s eta 0:00:30\n",
      "   ----------- ---------------------------- 57.1/204.2 MB 4.9 MB/s eta 0:00:30\n",
      "   ----------- ---------------------------- 57.9/204.2 MB 4.9 MB/s eta 0:00:30\n",
      "   ----------- ---------------------------- 59.2/204.2 MB 5.0 MB/s eta 0:00:30\n",
      "   ----------- ---------------------------- 60.6/204.2 MB 5.0 MB/s eta 0:00:29\n",
      "   ------------ --------------------------- 62.4/204.2 MB 5.0 MB/s eta 0:00:29\n",
      "   ------------ --------------------------- 64.2/204.2 MB 5.1 MB/s eta 0:00:28\n",
      "   ------------ --------------------------- 65.5/204.2 MB 5.1 MB/s eta 0:00:27\n",
      "   ------------ --------------------------- 66.1/204.2 MB 5.1 MB/s eta 0:00:28\n",
      "   ------------- -------------------------- 67.1/204.2 MB 5.1 MB/s eta 0:00:28\n",
      "   ------------- -------------------------- 68.4/204.2 MB 5.1 MB/s eta 0:00:27\n",
      "   ------------- -------------------------- 69.5/204.2 MB 5.1 MB/s eta 0:00:27\n",
      "   ------------- -------------------------- 70.3/204.2 MB 5.1 MB/s eta 0:00:27\n",
      "   ------------- -------------------------- 71.0/204.2 MB 5.1 MB/s eta 0:00:27\n",
      "   -------------- ------------------------- 72.4/204.2 MB 5.1 MB/s eta 0:00:26\n",
      "   -------------- ------------------------- 73.9/204.2 MB 5.1 MB/s eta 0:00:26\n",
      "   -------------- ------------------------- 76.3/204.2 MB 5.2 MB/s eta 0:00:25\n",
      "   --------------- ------------------------ 77.9/204.2 MB 5.2 MB/s eta 0:00:25\n",
      "   --------------- ------------------------ 78.9/204.2 MB 5.2 MB/s eta 0:00:25\n",
      "   --------------- ------------------------ 80.0/204.2 MB 5.2 MB/s eta 0:00:24\n",
      "   --------------- ------------------------ 81.3/204.2 MB 5.2 MB/s eta 0:00:24\n",
      "   ---------------- ----------------------- 82.6/204.2 MB 5.2 MB/s eta 0:00:24\n",
      "   ---------------- ----------------------- 83.4/204.2 MB 5.2 MB/s eta 0:00:24\n",
      "   ---------------- ----------------------- 84.1/204.2 MB 5.2 MB/s eta 0:00:24\n",
      "   ---------------- ----------------------- 84.9/204.2 MB 5.2 MB/s eta 0:00:24\n",
      "   ---------------- ----------------------- 86.0/204.2 MB 5.2 MB/s eta 0:00:23\n",
      "   ----------------- ---------------------- 87.3/204.2 MB 5.2 MB/s eta 0:00:23\n",
      "   ----------------- ---------------------- 88.9/204.2 MB 5.2 MB/s eta 0:00:23\n",
      "   ----------------- ---------------------- 89.9/204.2 MB 5.2 MB/s eta 0:00:22\n",
      "   ----------------- ---------------------- 91.8/204.2 MB 5.3 MB/s eta 0:00:22\n",
      "   ------------------ --------------------- 93.6/204.2 MB 5.3 MB/s eta 0:00:21\n",
      "   ------------------ --------------------- 95.2/204.2 MB 5.3 MB/s eta 0:00:21\n",
      "   ------------------ --------------------- 96.5/204.2 MB 5.3 MB/s eta 0:00:21\n",
      "   ------------------- -------------------- 98.3/204.2 MB 5.4 MB/s eta 0:00:20\n",
      "   ------------------- -------------------- 99.9/204.2 MB 5.4 MB/s eta 0:00:20\n",
      "   ------------------- -------------------- 101.2/204.2 MB 5.4 MB/s eta 0:00:20\n",
      "   -------------------- ------------------- 102.2/204.2 MB 5.4 MB/s eta 0:00:19\n",
      "   -------------------- ------------------- 103.3/204.2 MB 5.4 MB/s eta 0:00:19\n",
      "   -------------------- ------------------- 103.5/204.2 MB 5.4 MB/s eta 0:00:19\n",
      "   -------------------- ------------------- 103.8/204.2 MB 5.3 MB/s eta 0:00:19\n",
      "   -------------------- ------------------- 104.1/204.2 MB 5.3 MB/s eta 0:00:19\n",
      "   -------------------- ------------------- 104.1/204.2 MB 5.3 MB/s eta 0:00:19\n",
      "   -------------------- ------------------- 104.1/204.2 MB 5.3 MB/s eta 0:00:19\n",
      "   -------------------- ------------------- 104.1/204.2 MB 5.3 MB/s eta 0:00:19\n",
      "   -------------------- ------------------- 104.1/204.2 MB 5.3 MB/s eta 0:00:19\n",
      "   -------------------- ------------------- 104.1/204.2 MB 5.3 MB/s eta 0:00:19\n",
      "   -------------------- ------------------- 104.6/204.2 MB 5.0 MB/s eta 0:00:20\n",
      "   -------------------- ------------------- 105.9/204.2 MB 5.0 MB/s eta 0:00:20\n",
      "   --------------------- ------------------ 107.7/204.2 MB 5.0 MB/s eta 0:00:20\n",
      "   --------------------- ------------------ 109.6/204.2 MB 5.1 MB/s eta 0:00:19\n",
      "   --------------------- ------------------ 111.1/204.2 MB 5.1 MB/s eta 0:00:19\n",
      "   ---------------------- ----------------- 112.7/204.2 MB 5.1 MB/s eta 0:00:18\n",
      "   ---------------------- ----------------- 114.6/204.2 MB 5.1 MB/s eta 0:00:18\n",
      "   ---------------------- ----------------- 115.6/204.2 MB 5.2 MB/s eta 0:00:18\n",
      "   ---------------------- ----------------- 115.6/204.2 MB 5.2 MB/s eta 0:00:18\n",
      "   ---------------------- ----------------- 115.6/204.2 MB 5.2 MB/s eta 0:00:18\n",
      "   ---------------------- ----------------- 115.6/204.2 MB 5.2 MB/s eta 0:00:18\n",
      "   ---------------------- ----------------- 116.1/204.2 MB 5.0 MB/s eta 0:00:18\n",
      "   ---------------------- ----------------- 116.1/204.2 MB 5.0 MB/s eta 0:00:18\n",
      "   ---------------------- ----------------- 116.4/204.2 MB 4.9 MB/s eta 0:00:18\n",
      "   ---------------------- ----------------- 116.9/204.2 MB 4.9 MB/s eta 0:00:18\n",
      "   ---------------------- ----------------- 116.9/204.2 MB 4.9 MB/s eta 0:00:18\n",
      "   ----------------------- ---------------- 117.7/204.2 MB 4.8 MB/s eta 0:00:18\n",
      "   ----------------------- ---------------- 118.0/204.2 MB 4.8 MB/s eta 0:00:18\n",
      "   ----------------------- ---------------- 118.0/204.2 MB 4.8 MB/s eta 0:00:18\n",
      "   ----------------------- ---------------- 118.0/204.2 MB 4.8 MB/s eta 0:00:18\n",
      "   ----------------------- ---------------- 118.0/204.2 MB 4.8 MB/s eta 0:00:18\n",
      "   ----------------------- ---------------- 118.0/204.2 MB 4.8 MB/s eta 0:00:18\n",
      "   ----------------------- ---------------- 118.0/204.2 MB 4.8 MB/s eta 0:00:18\n",
      "   ----------------------- ---------------- 118.2/204.2 MB 4.6 MB/s eta 0:00:19\n",
      "   ----------------------- ---------------- 118.2/204.2 MB 4.6 MB/s eta 0:00:19\n",
      "   ----------------------- ---------------- 118.2/204.2 MB 4.6 MB/s eta 0:00:19\n",
      "   ----------------------- ---------------- 118.2/204.2 MB 4.6 MB/s eta 0:00:19\n",
      "   ----------------------- ---------------- 118.2/204.2 MB 4.6 MB/s eta 0:00:19\n",
      "   ----------------------- ---------------- 118.5/204.2 MB 4.4 MB/s eta 0:00:20\n",
      "   ----------------------- ---------------- 118.5/204.2 MB 4.4 MB/s eta 0:00:20\n",
      "   ----------------------- ---------------- 118.5/204.2 MB 4.4 MB/s eta 0:00:20\n",
      "   ----------------------- ---------------- 118.5/204.2 MB 4.4 MB/s eta 0:00:20\n",
      "   ----------------------- ---------------- 118.5/204.2 MB 4.4 MB/s eta 0:00:20\n",
      "   ----------------------- ---------------- 118.8/204.2 MB 4.3 MB/s eta 0:00:20\n",
      "   ----------------------- ---------------- 118.8/204.2 MB 4.3 MB/s eta 0:00:20\n",
      "   ----------------------- ---------------- 119.3/204.2 MB 4.2 MB/s eta 0:00:21\n",
      "   ----------------------- ---------------- 120.1/204.2 MB 4.2 MB/s eta 0:00:21\n",
      "   ----------------------- ---------------- 120.8/204.2 MB 4.2 MB/s eta 0:00:20\n",
      "   ----------------------- ---------------- 121.1/204.2 MB 4.2 MB/s eta 0:00:20\n",
      "   ----------------------- ---------------- 121.4/204.2 MB 4.2 MB/s eta 0:00:20\n",
      "   ----------------------- ---------------- 121.9/204.2 MB 4.1 MB/s eta 0:00:20\n",
      "   ------------------------ --------------- 122.7/204.2 MB 4.1 MB/s eta 0:00:20\n",
      "   ------------------------ --------------- 122.9/204.2 MB 4.1 MB/s eta 0:00:20\n",
      "   ------------------------ --------------- 122.9/204.2 MB 4.1 MB/s eta 0:00:20\n",
      "   ------------------------ --------------- 122.9/204.2 MB 4.1 MB/s eta 0:00:20\n",
      "   ------------------------ --------------- 122.9/204.2 MB 4.1 MB/s eta 0:00:20\n",
      "   ------------------------ --------------- 123.5/204.2 MB 4.0 MB/s eta 0:00:21\n",
      "   ------------------------ --------------- 124.3/204.2 MB 4.0 MB/s eta 0:00:21\n",
      "   ------------------------ --------------- 125.6/204.2 MB 4.0 MB/s eta 0:00:20\n",
      "   ------------------------ --------------- 126.6/204.2 MB 4.0 MB/s eta 0:00:20\n",
      "   ------------------------ --------------- 127.4/204.2 MB 4.0 MB/s eta 0:00:20\n",
      "   ------------------------- -------------- 128.5/204.2 MB 3.9 MB/s eta 0:00:20\n",
      "   ------------------------- -------------- 129.5/204.2 MB 3.9 MB/s eta 0:00:19\n",
      "   ------------------------- -------------- 130.8/204.2 MB 4.0 MB/s eta 0:00:19\n",
      "   ------------------------- -------------- 132.4/204.2 MB 4.0 MB/s eta 0:00:18\n",
      "   -------------------------- ------------- 134.2/204.2 MB 4.0 MB/s eta 0:00:18\n",
      "   -------------------------- ------------- 135.5/204.2 MB 4.0 MB/s eta 0:00:18\n",
      "   -------------------------- ------------- 136.3/204.2 MB 4.0 MB/s eta 0:00:17\n",
      "   -------------------------- ------------- 137.6/204.2 MB 4.1 MB/s eta 0:00:17\n",
      "   --------------------------- ------------ 138.9/204.2 MB 4.1 MB/s eta 0:00:17\n",
      "   --------------------------- ------------ 140.5/204.2 MB 4.1 MB/s eta 0:00:16\n",
      "   --------------------------- ------------ 141.6/204.2 MB 4.1 MB/s eta 0:00:16\n",
      "   --------------------------- ------------ 142.9/204.2 MB 4.1 MB/s eta 0:00:15\n",
      "   ---------------------------- ----------- 144.2/204.2 MB 4.2 MB/s eta 0:00:15\n",
      "   ---------------------------- ----------- 145.8/204.2 MB 4.2 MB/s eta 0:00:14\n",
      "   ---------------------------- ----------- 147.1/204.2 MB 4.3 MB/s eta 0:00:14\n",
      "   ----------------------------- ---------- 148.6/204.2 MB 4.3 MB/s eta 0:00:13\n",
      "   ----------------------------- ---------- 149.9/204.2 MB 4.3 MB/s eta 0:00:13\n",
      "   ----------------------------- ---------- 151.5/204.2 MB 4.4 MB/s eta 0:00:13\n",
      "   ----------------------------- ---------- 152.8/204.2 MB 4.4 MB/s eta 0:00:12\n",
      "   ------------------------------ --------- 154.4/204.2 MB 4.5 MB/s eta 0:00:12\n",
      "   ------------------------------ --------- 156.0/204.2 MB 4.5 MB/s eta 0:00:11\n",
      "   ------------------------------ --------- 157.3/204.2 MB 4.5 MB/s eta 0:00:11\n",
      "   ------------------------------- -------- 158.3/204.2 MB 4.5 MB/s eta 0:00:11\n",
      "   ------------------------------- -------- 160.2/204.2 MB 4.5 MB/s eta 0:00:10\n",
      "   ------------------------------- -------- 161.7/204.2 MB 4.5 MB/s eta 0:00:10\n",
      "   ------------------------------- -------- 163.3/204.2 MB 4.5 MB/s eta 0:00:10\n",
      "   -------------------------------- ------- 164.9/204.2 MB 4.5 MB/s eta 0:00:09\n",
      "   -------------------------------- ------- 166.7/204.2 MB 4.5 MB/s eta 0:00:09\n",
      "   -------------------------------- ------- 167.8/204.2 MB 4.5 MB/s eta 0:00:09\n",
      "   --------------------------------- ------ 169.3/204.2 MB 4.5 MB/s eta 0:00:08\n",
      "   --------------------------------- ------ 170.9/204.2 MB 4.5 MB/s eta 0:00:08\n",
      "   --------------------------------- ------ 172.5/204.2 MB 4.5 MB/s eta 0:00:08\n",
      "   ---------------------------------- ----- 174.1/204.2 MB 4.5 MB/s eta 0:00:07\n",
      "   ---------------------------------- ----- 175.4/204.2 MB 4.5 MB/s eta 0:00:07\n",
      "   ---------------------------------- ----- 176.4/204.2 MB 4.5 MB/s eta 0:00:07\n",
      "   ---------------------------------- ----- 177.5/204.2 MB 4.5 MB/s eta 0:00:06\n",
      "   ----------------------------------- ---- 179.0/204.2 MB 4.5 MB/s eta 0:00:06\n",
      "   ----------------------------------- ---- 179.8/204.2 MB 4.5 MB/s eta 0:00:06\n",
      "   ----------------------------------- ---- 181.4/204.2 MB 4.5 MB/s eta 0:00:06\n",
      "   ----------------------------------- ---- 183.2/204.2 MB 4.6 MB/s eta 0:00:05\n",
      "   ------------------------------------ --- 184.8/204.2 MB 4.6 MB/s eta 0:00:05\n",
      "   ------------------------------------ --- 186.4/204.2 MB 4.6 MB/s eta 0:00:04\n",
      "   ------------------------------------ --- 187.7/204.2 MB 4.6 MB/s eta 0:00:04\n",
      "   ------------------------------------- -- 189.0/204.2 MB 4.6 MB/s eta 0:00:04\n",
      "   ------------------------------------- -- 190.6/204.2 MB 4.6 MB/s eta 0:00:03\n",
      "   ------------------------------------- -- 191.9/204.2 MB 4.6 MB/s eta 0:00:03\n",
      "   ------------------------------------- -- 193.5/204.2 MB 4.6 MB/s eta 0:00:03\n",
      "   -------------------------------------- - 194.8/204.2 MB 4.6 MB/s eta 0:00:03\n",
      "   -------------------------------------- - 196.3/204.2 MB 4.6 MB/s eta 0:00:02\n",
      "   -------------------------------------- - 197.4/204.2 MB 4.6 MB/s eta 0:00:02\n",
      "   -------------------------------------- - 199.0/204.2 MB 4.6 MB/s eta 0:00:02\n",
      "   ---------------------------------------  200.5/204.2 MB 4.6 MB/s eta 0:00:01\n",
      "   ---------------------------------------  202.1/204.2 MB 4.6 MB/s eta 0:00:01\n",
      "   ---------------------------------------  203.7/204.2 MB 4.6 MB/s eta 0:00:01\n",
      "   ---------------------------------------  203.9/204.2 MB 4.6 MB/s eta 0:00:01\n",
      "   ---------------------------------------  203.9/204.2 MB 4.6 MB/s eta 0:00:01\n",
      "   ---------------------------------------  203.9/204.2 MB 4.6 MB/s eta 0:00:01\n",
      "   ---------------------------------------- 204.2/204.2 MB 4.5 MB/s eta 0:00:00\n",
      "Downloading sympy-1.13.1-py3-none-any.whl (6.2 MB)\n",
      "   ---------------------------------------- 0.0/6.2 MB ? eta -:--:--\n",
      "   ---------- ----------------------------- 1.6/6.2 MB 7.7 MB/s eta 0:00:01\n",
      "   -------------------- ------------------- 3.1/6.2 MB 8.4 MB/s eta 0:00:01\n",
      "   ------------------------- -------------- 3.9/6.2 MB 6.5 MB/s eta 0:00:01\n",
      "   -------------------------------------- - 6.0/6.2 MB 7.2 MB/s eta 0:00:01\n",
      "   ---------------------------------------- 6.2/6.2 MB 6.9 MB/s eta 0:00:00\n",
      "Downloading transformers-4.49.0-py3-none-any.whl (10.0 MB)\n",
      "   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--\n",
      "   ------- -------------------------------- 1.8/10.0 MB 8.4 MB/s eta 0:00:01\n",
      "   -------------- ------------------------- 3.7/10.0 MB 9.1 MB/s eta 0:00:01\n",
      "   --------------------- ------------------ 5.2/10.0 MB 8.4 MB/s eta 0:00:01\n",
      "   --------------------------- ------------ 6.8/10.0 MB 8.2 MB/s eta 0:00:01\n",
      "   --------------------------------- ------ 8.4/10.0 MB 8.1 MB/s eta 0:00:01\n",
      "   -------------------------------------- - 9.7/10.0 MB 8.2 MB/s eta 0:00:01\n",
      "   ---------------------------------------- 10.0/10.0 MB 7.2 MB/s eta 0:00:00\n",
      "Downloading fsspec-2025.2.0-py3-none-any.whl (184 kB)\n",
      "Downloading PyYAML-6.0.2-cp311-cp311-win_amd64.whl (161 kB)\n",
      "Downloading safetensors-0.5.3-cp38-abi3-win_amd64.whl (308 kB)\n",
      "Downloading tokenizers-0.21.0-cp39-abi3-win_amd64.whl (2.4 MB)\n",
      "   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--\n",
      "   -------------------------- ------------- 1.6/2.4 MB 7.0 MB/s eta 0:00:01\n",
      "   ---------------------------------------  2.4/2.4 MB 7.5 MB/s eta 0:00:01\n",
      "   ---------------------------------------- 2.4/2.4 MB 5.2 MB/s eta 0:00:00\n",
      "Downloading filelock-3.17.0-py3-none-any.whl (16 kB)\n",
      "Downloading networkx-3.4.2-py3-none-any.whl (1.7 MB)\n",
      "   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--\n",
      "   ------------------------------------ --- 1.6/1.7 MB 9.3 MB/s eta 0:00:01\n",
      "   ---------------------------------------- 1.7/1.7 MB 4.7 MB/s eta 0:00:00\n",
      "Downloading mpmath-1.3.0-py3-none-any.whl (536 kB)\n",
      "   ---------------------------------------- 0.0/536.2 kB ? eta -:--:--\n",
      "   ---------------------------------------- 536.2/536.2 kB 5.8 MB/s eta 0:00:00\n",
      "Installing collected packages: mpmath, sympy, safetensors, pyyaml, networkx, fsspec, filelock, torch, huggingface-hub, tokenizers, transformers, sentence-transformers\n",
      "Successfully installed filelock-3.17.0 fsspec-2025.2.0 huggingface-hub-0.29.1 mpmath-1.3.0 networkx-3.4.2 pyyaml-6.0.2 safetensors-0.5.3 sentence-transformers-3.4.1 sympy-1.13.1 tokenizers-0.21.0 torch-2.6.0 transformers-4.49.0\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install sentence-transformers scikit-learn pandas numpy"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "from sentence_transformers import SentenceTransformer\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.metrics import accuracy_score\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Load pre-trained embedding model (FREE)\n",
    "model = SentenceTransformer(\"sentence-transformers/all-MiniLM-L6-v2\")\n",
    "\n",
    "# Load datasets (each file contains one article per line)\n",
    "with open(\"Fake.csv\", \"r\", encoding=\"utf-8\") as f:\n",
    "    fake_news = f.readlines()\n",
    "\n",
    "with open(\"True.csv\", \"r\", encoding=\"utf-8\") as f:\n",
    "    real_news = f.readlines()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create DataFrame\n",
    "df_fake = pd.DataFrame({\"text\": fake_news, \"label\": 1})  # Fake news = 1\n",
    "df_real = pd.DataFrame({\"text\": real_news, \"label\": 0})  # Real news = 0\n",
    "\n",
    "df = pd.concat([df_fake, df_real], ignore_index=True)\n",
    "\n",
    "# Generate embeddings\n",
    "df[\"embeddings\"] = df[\"text\"].apply(lambda x: model.encode(x.strip()))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Prepare training data\n",
    "X = np.vstack(df[\"embeddings\"].values)\n",
    "y = df[\"label\"].values\n",
    "\n",
    "# Split dataset\n",
    "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<style>#sk-container-id-1 {\n",
       "  /* Definition of color scheme common for light and dark mode */\n",
       "  --sklearn-color-text: #000;\n",
       "  --sklearn-color-text-muted: #666;\n",
       "  --sklearn-color-line: gray;\n",
       "  /* Definition of color scheme for unfitted estimators */\n",
       "  --sklearn-color-unfitted-level-0: #fff5e6;\n",
       "  --sklearn-color-unfitted-level-1: #f6e4d2;\n",
       "  --sklearn-color-unfitted-level-2: #ffe0b3;\n",
       "  --sklearn-color-unfitted-level-3: chocolate;\n",
       "  /* Definition of color scheme for fitted estimators */\n",
       "  --sklearn-color-fitted-level-0: #f0f8ff;\n",
       "  --sklearn-color-fitted-level-1: #d4ebff;\n",
       "  --sklearn-color-fitted-level-2: #b3dbfd;\n",
       "  --sklearn-color-fitted-level-3: cornflowerblue;\n",
       "\n",
       "  /* Specific color for light theme */\n",
       "  --sklearn-color-text-on-default-background: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, black)));\n",
       "  --sklearn-color-background: var(--sg-background-color, var(--theme-background, var(--jp-layout-color0, white)));\n",
       "  --sklearn-color-border-box: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, black)));\n",
       "  --sklearn-color-icon: #696969;\n",
       "\n",
       "  @media (prefers-color-scheme: dark) {\n",
       "    /* Redefinition of color scheme for dark theme */\n",
       "    --sklearn-color-text-on-default-background: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, white)));\n",
       "    --sklearn-color-background: var(--sg-background-color, var(--theme-background, var(--jp-layout-color0, #111)));\n",
       "    --sklearn-color-border-box: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, white)));\n",
       "    --sklearn-color-icon: #878787;\n",
       "  }\n",
       "}\n",
       "\n",
       "#sk-container-id-1 {\n",
       "  color: var(--sklearn-color-text);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 pre {\n",
       "  padding: 0;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 input.sk-hidden--visually {\n",
       "  border: 0;\n",
       "  clip: rect(1px 1px 1px 1px);\n",
       "  clip: rect(1px, 1px, 1px, 1px);\n",
       "  height: 1px;\n",
       "  margin: -1px;\n",
       "  overflow: hidden;\n",
       "  padding: 0;\n",
       "  position: absolute;\n",
       "  width: 1px;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-dashed-wrapped {\n",
       "  border: 1px dashed var(--sklearn-color-line);\n",
       "  margin: 0 0.4em 0.5em 0.4em;\n",
       "  box-sizing: border-box;\n",
       "  padding-bottom: 0.4em;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-container {\n",
       "  /* jupyter's `normalize.less` sets `[hidden] { display: none; }`\n",
       "     but bootstrap.min.css set `[hidden] { display: none !important; }`\n",
       "     so we also need the `!important` here to be able to override the\n",
       "     default hidden behavior on the sphinx rendered scikit-learn.org.\n",
       "     See: https://github.com/scikit-learn/scikit-learn/issues/21755 */\n",
       "  display: inline-block !important;\n",
       "  position: relative;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-text-repr-fallback {\n",
       "  display: none;\n",
       "}\n",
       "\n",
       "div.sk-parallel-item,\n",
       "div.sk-serial,\n",
       "div.sk-item {\n",
       "  /* draw centered vertical line to link estimators */\n",
       "  background-image: linear-gradient(var(--sklearn-color-text-on-default-background), var(--sklearn-color-text-on-default-background));\n",
       "  background-size: 2px 100%;\n",
       "  background-repeat: no-repeat;\n",
       "  background-position: center center;\n",
       "}\n",
       "\n",
       "/* Parallel-specific style estimator block */\n",
       "\n",
       "#sk-container-id-1 div.sk-parallel-item::after {\n",
       "  content: \"\";\n",
       "  width: 100%;\n",
       "  border-bottom: 2px solid var(--sklearn-color-text-on-default-background);\n",
       "  flex-grow: 1;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-parallel {\n",
       "  display: flex;\n",
       "  align-items: stretch;\n",
       "  justify-content: center;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "  position: relative;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-parallel-item {\n",
       "  display: flex;\n",
       "  flex-direction: column;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-parallel-item:first-child::after {\n",
       "  align-self: flex-end;\n",
       "  width: 50%;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-parallel-item:last-child::after {\n",
       "  align-self: flex-start;\n",
       "  width: 50%;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-parallel-item:only-child::after {\n",
       "  width: 0;\n",
       "}\n",
       "\n",
       "/* Serial-specific style estimator block */\n",
       "\n",
       "#sk-container-id-1 div.sk-serial {\n",
       "  display: flex;\n",
       "  flex-direction: column;\n",
       "  align-items: center;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "  padding-right: 1em;\n",
       "  padding-left: 1em;\n",
       "}\n",
       "\n",
       "\n",
       "/* Toggleable style: style used for estimator/Pipeline/ColumnTransformer box that is\n",
       "clickable and can be expanded/collapsed.\n",
       "- Pipeline and ColumnTransformer use this feature and define the default style\n",
       "- Estimators will overwrite some part of the style using the `sk-estimator` class\n",
       "*/\n",
       "\n",
       "/* Pipeline and ColumnTransformer style (default) */\n",
       "\n",
       "#sk-container-id-1 div.sk-toggleable {\n",
       "  /* Default theme specific background. It is overwritten whether we have a\n",
       "  specific estimator or a Pipeline/ColumnTransformer */\n",
       "  background-color: var(--sklearn-color-background);\n",
       "}\n",
       "\n",
       "/* Toggleable label */\n",
       "#sk-container-id-1 label.sk-toggleable__label {\n",
       "  cursor: pointer;\n",
       "  display: flex;\n",
       "  width: 100%;\n",
       "  margin-bottom: 0;\n",
       "  padding: 0.5em;\n",
       "  box-sizing: border-box;\n",
       "  text-align: center;\n",
       "  align-items: start;\n",
       "  justify-content: space-between;\n",
       "  gap: 0.5em;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 label.sk-toggleable__label .caption {\n",
       "  font-size: 0.6rem;\n",
       "  font-weight: lighter;\n",
       "  color: var(--sklearn-color-text-muted);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 label.sk-toggleable__label-arrow:before {\n",
       "  /* Arrow on the left of the label */\n",
       "  content: \"▸\";\n",
       "  float: left;\n",
       "  margin-right: 0.25em;\n",
       "  color: var(--sklearn-color-icon);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 label.sk-toggleable__label-arrow:hover:before {\n",
       "  color: var(--sklearn-color-text);\n",
       "}\n",
       "\n",
       "/* Toggleable content - dropdown */\n",
       "\n",
       "#sk-container-id-1 div.sk-toggleable__content {\n",
       "  max-height: 0;\n",
       "  max-width: 0;\n",
       "  overflow: hidden;\n",
       "  text-align: left;\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-toggleable__content.fitted {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-toggleable__content pre {\n",
       "  margin: 0.2em;\n",
       "  border-radius: 0.25em;\n",
       "  color: var(--sklearn-color-text);\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-toggleable__content.fitted pre {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 input.sk-toggleable__control:checked~div.sk-toggleable__content {\n",
       "  /* Expand drop-down */\n",
       "  max-height: 200px;\n",
       "  max-width: 100%;\n",
       "  overflow: auto;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 input.sk-toggleable__control:checked~label.sk-toggleable__label-arrow:before {\n",
       "  content: \"▾\";\n",
       "}\n",
       "\n",
       "/* Pipeline/ColumnTransformer-specific style */\n",
       "\n",
       "#sk-container-id-1 div.sk-label input.sk-toggleable__control:checked~label.sk-toggleable__label {\n",
       "  color: var(--sklearn-color-text);\n",
       "  background-color: var(--sklearn-color-unfitted-level-2);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-label.fitted input.sk-toggleable__control:checked~label.sk-toggleable__label {\n",
       "  background-color: var(--sklearn-color-fitted-level-2);\n",
       "}\n",
       "\n",
       "/* Estimator-specific style */\n",
       "\n",
       "/* Colorize estimator box */\n",
       "#sk-container-id-1 div.sk-estimator input.sk-toggleable__control:checked~label.sk-toggleable__label {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-2);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-estimator.fitted input.sk-toggleable__control:checked~label.sk-toggleable__label {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-2);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-label label.sk-toggleable__label,\n",
       "#sk-container-id-1 div.sk-label label {\n",
       "  /* The background is the default theme color */\n",
       "  color: var(--sklearn-color-text-on-default-background);\n",
       "}\n",
       "\n",
       "/* On hover, darken the color of the background */\n",
       "#sk-container-id-1 div.sk-label:hover label.sk-toggleable__label {\n",
       "  color: var(--sklearn-color-text);\n",
       "  background-color: var(--sklearn-color-unfitted-level-2);\n",
       "}\n",
       "\n",
       "/* Label box, darken color on hover, fitted */\n",
       "#sk-container-id-1 div.sk-label.fitted:hover label.sk-toggleable__label.fitted {\n",
       "  color: var(--sklearn-color-text);\n",
       "  background-color: var(--sklearn-color-fitted-level-2);\n",
       "}\n",
       "\n",
       "/* Estimator label */\n",
       "\n",
       "#sk-container-id-1 div.sk-label label {\n",
       "  font-family: monospace;\n",
       "  font-weight: bold;\n",
       "  display: inline-block;\n",
       "  line-height: 1.2em;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-label-container {\n",
       "  text-align: center;\n",
       "}\n",
       "\n",
       "/* Estimator-specific */\n",
       "#sk-container-id-1 div.sk-estimator {\n",
       "  font-family: monospace;\n",
       "  border: 1px dotted var(--sklearn-color-border-box);\n",
       "  border-radius: 0.25em;\n",
       "  box-sizing: border-box;\n",
       "  margin-bottom: 0.5em;\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-estimator.fitted {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-0);\n",
       "}\n",
       "\n",
       "/* on hover */\n",
       "#sk-container-id-1 div.sk-estimator:hover {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-2);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-estimator.fitted:hover {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-2);\n",
       "}\n",
       "\n",
       "/* Specification for estimator info (e.g. \"i\" and \"?\") */\n",
       "\n",
       "/* Common style for \"i\" and \"?\" */\n",
       "\n",
       ".sk-estimator-doc-link,\n",
       "a:link.sk-estimator-doc-link,\n",
       "a:visited.sk-estimator-doc-link {\n",
       "  float: right;\n",
       "  font-size: smaller;\n",
       "  line-height: 1em;\n",
       "  font-family: monospace;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "  border-radius: 1em;\n",
       "  height: 1em;\n",
       "  width: 1em;\n",
       "  text-decoration: none !important;\n",
       "  margin-left: 0.5em;\n",
       "  text-align: center;\n",
       "  /* unfitted */\n",
       "  border: var(--sklearn-color-unfitted-level-1) 1pt solid;\n",
       "  color: var(--sklearn-color-unfitted-level-1);\n",
       "}\n",
       "\n",
       ".sk-estimator-doc-link.fitted,\n",
       "a:link.sk-estimator-doc-link.fitted,\n",
       "a:visited.sk-estimator-doc-link.fitted {\n",
       "  /* fitted */\n",
       "  border: var(--sklearn-color-fitted-level-1) 1pt solid;\n",
       "  color: var(--sklearn-color-fitted-level-1);\n",
       "}\n",
       "\n",
       "/* On hover */\n",
       "div.sk-estimator:hover .sk-estimator-doc-link:hover,\n",
       ".sk-estimator-doc-link:hover,\n",
       "div.sk-label-container:hover .sk-estimator-doc-link:hover,\n",
       ".sk-estimator-doc-link:hover {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-3);\n",
       "  color: var(--sklearn-color-background);\n",
       "  text-decoration: none;\n",
       "}\n",
       "\n",
       "div.sk-estimator.fitted:hover .sk-estimator-doc-link.fitted:hover,\n",
       ".sk-estimator-doc-link.fitted:hover,\n",
       "div.sk-label-container:hover .sk-estimator-doc-link.fitted:hover,\n",
       ".sk-estimator-doc-link.fitted:hover {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-3);\n",
       "  color: var(--sklearn-color-background);\n",
       "  text-decoration: none;\n",
       "}\n",
       "\n",
       "/* Span, style for the box shown on hovering the info icon */\n",
       ".sk-estimator-doc-link span {\n",
       "  display: none;\n",
       "  z-index: 9999;\n",
       "  position: relative;\n",
       "  font-weight: normal;\n",
       "  right: .2ex;\n",
       "  padding: .5ex;\n",
       "  margin: .5ex;\n",
       "  width: min-content;\n",
       "  min-width: 20ex;\n",
       "  max-width: 50ex;\n",
       "  color: var(--sklearn-color-text);\n",
       "  box-shadow: 2pt 2pt 4pt #999;\n",
       "  /* unfitted */\n",
       "  background: var(--sklearn-color-unfitted-level-0);\n",
       "  border: .5pt solid var(--sklearn-color-unfitted-level-3);\n",
       "}\n",
       "\n",
       ".sk-estimator-doc-link.fitted span {\n",
       "  /* fitted */\n",
       "  background: var(--sklearn-color-fitted-level-0);\n",
       "  border: var(--sklearn-color-fitted-level-3);\n",
       "}\n",
       "\n",
       ".sk-estimator-doc-link:hover span {\n",
       "  display: block;\n",
       "}\n",
       "\n",
       "/* \"?\"-specific style due to the `<a>` HTML tag */\n",
       "\n",
       "#sk-container-id-1 a.estimator_doc_link {\n",
       "  float: right;\n",
       "  font-size: 1rem;\n",
       "  line-height: 1em;\n",
       "  font-family: monospace;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "  border-radius: 1rem;\n",
       "  height: 1rem;\n",
       "  width: 1rem;\n",
       "  text-decoration: none;\n",
       "  /* unfitted */\n",
       "  color: var(--sklearn-color-unfitted-level-1);\n",
       "  border: var(--sklearn-color-unfitted-level-1) 1pt solid;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 a.estimator_doc_link.fitted {\n",
       "  /* fitted */\n",
       "  border: var(--sklearn-color-fitted-level-1) 1pt solid;\n",
       "  color: var(--sklearn-color-fitted-level-1);\n",
       "}\n",
       "\n",
       "/* On hover */\n",
       "#sk-container-id-1 a.estimator_doc_link:hover {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-3);\n",
       "  color: var(--sklearn-color-background);\n",
       "  text-decoration: none;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 a.estimator_doc_link.fitted:hover {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-3);\n",
       "}\n",
       "</style><div id=\"sk-container-id-1\" class=\"sk-top-container\"><div class=\"sk-text-repr-fallback\"><pre>RandomForestClassifier(random_state=42)</pre><b>In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook. <br />On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.</b></div><div class=\"sk-container\" hidden><div class=\"sk-item\"><div class=\"sk-estimator fitted sk-toggleable\"><input class=\"sk-toggleable__control sk-hidden--visually\" id=\"sk-estimator-id-1\" type=\"checkbox\" checked><label for=\"sk-estimator-id-1\" class=\"sk-toggleable__label fitted sk-toggleable__label-arrow\"><div><div>RandomForestClassifier</div></div><div><a class=\"sk-estimator-doc-link fitted\" rel=\"noreferrer\" target=\"_blank\" href=\"https://scikit-learn.org/1.6/modules/generated/sklearn.ensemble.RandomForestClassifier.html\">?<span>Documentation for RandomForestClassifier</span></a><span class=\"sk-estimator-doc-link fitted\">i<span>Fitted</span></span></div></label><div class=\"sk-toggleable__content fitted\"><pre>RandomForestClassifier(random_state=42)</pre></div> </div></div></div></div>"
      ],
      "text/plain": [
       "RandomForestClassifier(random_state=42)"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Train classifier\n",
    "clf = RandomForestClassifier(n_estimators=100, random_state=42)\n",
    "clf.fit(X_train, y_train)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Model Accuracy: 0.93\n"
     ]
    }
   ],
   "source": [
    "# Predict on test set\n",
    "y_pred = clf.predict(X_test)\n",
    "\n",
    "# Evaluate model\n",
    "accuracy = accuracy_score(y_test, y_pred)\n",
    "print(f\"Model Accuracy: {accuracy:.2f}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Real News\n"
     ]
    }
   ],
   "source": [
    "# Example Prediction\n",
    "def predict_fake_news(text):\n",
    "    embedding = model.encode(text)\n",
    "    prediction = clf.predict([embedding])[0]\n",
    "    return \"Fake News\" if prediction == 1 else \"Real News\"\n",
    "\n",
    "# Test exampleMisinformation\n",
    "example_text = \"Trump says Russia probe will be fair, but timeline unclear: NYT\"\n",
    "print(predict_fake_news(example_text))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Real News\n"
     ]
    }
   ],
   "source": [
    "# Test exampleMisinformation\n",
    "example_text = \"Rainbow has 7 colors\"\n",
    "print(predict_fake_news(example_text))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Fake News\n"
     ]
    }
   ],
   "source": [
    "# Test exampleMisinformation\n",
    "example_text = \"Rainbow has 9 colors\"\n",
    "print(predict_fake_news(example_text))"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
